import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";
const badass = require("../assets/Headshot_Badass.jpg");
const sweet = require("../assets/Headshot_Sweet.jpg");

export default function Home() {
  return (
    <>
      <Head>
        <title>Mae Balen</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center py-20 h-screen w-full">
        <motion.div className="h-full rounded-lg overflow-hidden shadow-xl shadow-gray-800">
          <Image
            src={sweet}
            alt="sweet"
            className="object-cover w-full h-full"
          />
        </motion.div>
      </main>
    </>
  );
}
